### ISSUE TITLE
Copy/Paste not working as expected

### ISSUE THREAD

**Issue by iamjohnbarker** [Aurelain/react-style-editor#3]
Attempting to copy a value (or and portion of text) will actually copy all CSS text.
<img width="484" alt="Screenshot 2021-12-27 at 09 20 57" src="https://user-images.githubusercontent.com/7009061/147451162-49e58730-9eed-42a5-be3a-399260737f8d.png">

In this example, I would expect to only copy the 'white !important', however my entire CSS block is selected.

I suspect this is so you can copy/paste all CSS out of the input, however I can see a huge value in grabbing certain values for use on other selectors.

**Comment by iamjohnbarker** [comment]
Apologies, looks like perhaps this was on your wishlist already

**Comment by Aurelain** [comment]
Resolved in [v0.4.0](https://github.com/Aurelain/react-style-editor/releases/tag/v0.4.0) by allowing native copy when selection exists.

**Comment by iamjohnbarker** [comment]
Finally upgraded to v0.4.0 and this issue seems to still persist.
